### ISSUE TITLE
Welcome & Shoutout Rain arnt should the targets PFP

### ISSUE THREAD

**Issue by vj4sothername** [GForceWeb/EmoteOverlayTools#1]
Hello,

I found this while trying to resolve the same issue with vrflads code. Sadly welcome and shoutout arnt showing the users icons.

Cheers,
VJ

**Comment by GForceWeb** [comment]
That's odd, they are still working for me.

Try running with ?all to ensure everything is enabled and then try a shoutout with !so @username

If that still doesn't work, ensure your computer can access the DecAPI service by trying this in a browser replacing the username at the end with your twitch username, it should return a URL of your twitch avatar image:

https://decapi.me/twitch/avatar/username

**Comment by vj4sothername** [comment]
i can access decapi and get images, Lurk works well. just no first chat or shoutout. Used this link   https://gforceweb.github.io/EmoteOverlayTools/?all

Could it be an issue with streamerbot? What command should run for the !so?

edit: i did some playing in the back end and made some super basic changes.

line 149:   var username = wsdata.data.message.username;
line 185:   const sousername = lowermessage.substring(4);

They got them working for me. not a good way but its functional for now untill i can spend some time learnng JS

**Comment by GForceWeb** [comment]
Ah, you're absolutely right, Streamer.Bot had changed the user.name parameter to .username in the websocket data and I had already changed this on my local to patch it and thought I'd pushed that to the public repo but it looks like I didn't push it for the lurk command.

I've got a pretty big codebase refactor I'm nearly finished with to make things more readable and easier to expand upon that I'm looking to publish soon so I'll include that fix with that. Feel Free to use your locally modified file with the line 149 change in the meantime.

**Comment by vj4sothername** [comment]
Exctiting times!!! Do you have a recomened resource for someone with no knowledge of js to make their own anim,ation for it? for example, a stream of emotes spreading in the a corner or other specified location?


Okay so i've done a bit of playing and added these in to stop bots getting a first words shout out. Not sure if its functionality you might wanna add.

const bots = ["bot 1", "bot 2"];


              var username = "";
              if (bots.includes(wsdata.data.message.username) === false ){
                 username = wsdata.data.message.username;
              }

**Comment by GForceWeb** [comment]
So the animation library I use is called GSAP and they have pretty great docs. It's pretty straightforward to reverse-engineer a new animation from the existing code and then adjust the gsap animation code to control what the elements do. 

https://greensock.com/docs/v3

The code is generally split up into functions to do the following:

 - Trigger the event either by chat message or as part of kappagen/some other trigger
 - Create the Div/Divs for the animation, set a timeout for removal and trigger the animation function
 - Run the GSAP animation which is basically a series of tween commands to change CSS parameters to set values over a set duration
 
 This will be much cleaner and easy to work with after the refactored code is up as I've made these different types of functions clearly separated
 
As for excluding the bots it's not really been an issue for me. I only have SE and my custom bot used with SB and both of those have usually triggered their first words before I even go live. It's hard to cover every bot in a list especially if other users are using custom bots but I guess I could include the big well known bots in a list and allow custom bots to be specified in a URL parameter. I'll give that some thought

**Comment by vj4sothername** [comment]
Brilliant thanks for that. I'll start investigating!
